### ISSUE TITLE
Error BottomNavigation in android

### ISSUE THREAD

**Issue by pedicini** [NativeScript/nativescript-sdk-examples-ng#435]
SO Android 10 - OxigenOS, when parking the App and then reopening it, returns the following error

System.err: An uncaught Exception occurred on "main" thread.
System.err: Calling js method onStart failed
System.err: Error: java.lang.IllegalArgumentException: No view found for id 0x4 (unknown) for fragment FragmentBase_vendor_97639_32_TabFragmentImplementation{a875961 #3 id=0x4 android:bottomnavigation:4:1}
System.err: 
System.err: StackTrace:
System.err: push.../node_modules/@nativescript/core/ui/bottom-navigation/bottom-navigation.js.BottomNavigation.commitCurrentTransaction(file:///node_modules/@nativescript/core/ui/bottom-navigation/bottom-navigation.js:349:0)
System.err:     at push.../node_modules/@nativescript/core/ui/bottom-navigation/bottom-navigation.js.BottomNavigation.changeTab(file:///node_modules/@nativescript/core/ui/bottom-navigation/bottom-navigation.js:363:0)
System.err:     at push.../node_modules/@nativescript/core/ui/bottom-navigation/bottom-navigation.js.BottomNavigation.onLoaded(file:///node_modules/@nativescript/core/ui/bottom-navigation/bottom-navigation.js:290:0)
System.err:     at (file:///node_modules/@nativescript/core/ui/core/view-base/view-base.js:312:75)
System.err:     at push.../node_modules/@nativescript/core/ui/core/view-base/view-base.js.ViewBase.callFunctionWithSuper(file:///node_modules/@nativescript/core/ui/core/view-base/view-base.js:305:0)
System.err:     at push.../node_modules/@nativescript/core/ui/core/view-base/view-base.js.ViewBase.callLoaded(file:///node_modules/@nativescript/core/ui/core/view-base/view-base.js:312:0)
System.err:     at push.../node_modules/@nativescript/core/ui/core/view-base/view-base.js.ViewBase.loadView(file:///node_modules/@nativescript/core/ui/core/view-base/view-base.js:440:0)
System.err:     at (file:///node_modules/@nativescript/core/ui/core/view-base/view-base.js:234:0)
System.err:     at push.../node_modules/@nativescript/core/ui/layouts/layout-base-common.js.LayoutBaseCommon.eachChildView(file:///node_modules/@nativescript/core/ui/layouts/layout-base-common.js:125:0)
System.err:     at push.../node_modules/@nativescript/core/ui/core/view/view-common.js.ViewCommon.eachChild(file:///node_modules/@nativescript/core/ui/core/view/view-common.js:1010:0)
System.err:     at push.../node_modules/@nativescript/core/ui/core/view-base/view-base.js.ViewBase.onLoaded(file:///node_modules/@nativescript/core/ui/core/view-base/view-base.js:233:0)
System.err:     at push.../node_modules/@nativescript/core/ui/core/view/view.js.View.onLoaded(file:///node_modules/@nativescript/core/ui/core/view/view.js:246:0)
System.err:     at (file:///node_modules/@nativescript/core/ui/core/view-base/view-base.js:312:75)
System.err:     at push.../node_modules/@nativescript/core/ui/core/view-base/view-base.js.ViewBase.callFunctionWithSuper(file:///node_modules/@nativescript/core/ui/core/view-base/view-base.js:305:0)
System.err:     at push.../node_modules/@nativescript/core/ui/core/view-base/view-base.js.ViewBase.callLoaded(file:///node_modules/@nativescript/core/ui/core/view-base/view-base.js:312:0)
System.err:     at push.../node_modules/@nativescript/core/ui/core/view-base/view-base.js.ViewBase.loadView(file:///node_modules/@nativescript/core/ui/core/view-base/view-base.js:440:0)
System.err:     at (file:///node_modules/@nativescript/core/ui/core/view-base/view-base.js:234:0)
System.err:     at push.../node_modules/@nativescript/core/ui/layouts/layout-base-common.js.LayoutBaseCommon.eachChildView(file:///node_modules/@nativescript/core/ui/layouts/layout-base-common.js:125:0)
System.err:     at push.../node_modules/@nativescript/core/ui/core/view/view-common.js.ViewCommon.eachChild(file:///node_modules/@nativescript/core/ui/core/view/view-common.js:1010:0)
System.err:     at push.../node_modules/@nativescript/core/ui/core/view-base/view-base.js.ViewBase.onLoaded(file:///node_modules/@nativescript/core/ui/core/view-base/view-base.js:233:0)
System.err:     at push.../node_modules/@nativescript/core/ui/core/view/view.js.View.onLoaded(file:///node_modules/@nativescript/core/ui/core/view/view.js:246:0)
System.err:     at (file:///node_modules/@nativescript/core/ui/core/view-base/view-base.js:312:75)
System.err:     at push.../node_modules/@nativescript/core/ui/core/view-base/view-base.js.ViewBase.callFunctionWithSuper(file:///node_modules/@nativescript/core/ui/core/view-base/view-base.js:305:0)
System.err:     at push.../node_modules/@nativescript/core/ui/core/view-base/view-base.js.ViewBase.callLoaded(file:///node_modules/@nativescript/core/ui/core/view-base/view-base.js:312:0)
System.err:     at push.../node_modules/@nativescript/core/ui/core/view-base/view-base.js.ViewBase.loadView(file:///node_modules/@nativescript/core/ui/core/view-base/view-base.js:440:0)
System.err:     at (file:///node_modules/@nativescript/core/ui/core/view-base/view-base.js:234:0)
System.err:     at push.../node_modules/@nativescript/core/ui/content-view/content-view.js.ContentView.eachChildView(file:///node_modules/@nativescript/core/ui/content-view/content-view.js:70:0)
System.err:     at push.../node_modules/@nativescript/core/ui/page/page-common.js.PageBase.eachChildView(file:///node_modules/@nativescript/core/ui/page/page-common.js:126:0)
System.err:     at push.../node_modules/@nativescript/core/ui/core/view/view-common.js.ViewCommon.eachChild(file:///node_modules/@nativescript/core/ui/core/view/view-common.js:1010:0)
System.err:     at push.../node_modules/@nativescript/core/ui/core/view-base/view-base.js.ViewBase.onLoaded(file:///node_modules/@nativescript/core/ui/core/view-base/view-base.js:233:0)
System.err:     at push.../node_modules/@nativescript/core/ui/core/view/view.js.View.onLoaded(file:///node_modules/@nativescript/core/ui/core/view/view.js:246:0)
System.err:     at push.../node_modules/@nativescript/core/ui/page/page.js.Page.onLoaded(file:///node_modules/@nativescript/core/ui/page/page.js:43:0)
System.err:     at (file:///node_modules/@nativescript/core/ui/core/view-base/view-base.js:312:75)
System.err:     at push.../node_modules/@nativescript/core/ui/core/view-base/view-base.js.ViewBase.callFunctionWithSuper(file:///node_modules/@nativescript/core/ui/core/view-base/view-base.js:305:0)
System.err:     at push.../node_modules/@nativescript/core/ui/core/view-base/view-base.js.ViewBase.callLoaded(file:///node_modules/@nativescript/core/ui/core/view-base/view-base.js:312:0)
System.err:     at push.../node_modules/@nativescript/core/ui/core/view-base/view-base.js.ViewBase.loadView(file:///node_modules/@nativescript/core/ui/core/view-base/view-base.js:440:0)
System.err:     at (file:///node_modules/@nativescript/core/ui/core/view-base/view-base.js:234:0)
System.err:     at push.../node_modules/@nativescript/core/ui/frame/frame-common.js.FrameBase.eachChildView(file:///node_modules/@nativescript/core/ui/frame/frame-common.js:422:0)
System.err:     at push.../node_modules/@nativescript/core/ui/core/view/view-common.js.ViewCommon.eachChild(file:///node_modules/@nativescript/core/ui/core/view/view-common.js:1010:0)
System.err:     at push.../node_modules/@nativescript/core/ui/core/view-base/view-base.js.ViewBase.onLoaded(file:///node_modules/@nativescript/core/ui/core/view-base/view-base.js:233:0)
System.err:     at push.../node_modules/@nativescript/core/ui/core/view/view.js.View.onLoaded(file:///node_modules/@nativescript/core/ui/core/view/view.js:246:0)
System.err:     at push.../node_modules/@nativescript/core/ui/frame/frame-common.js.FrameBase.onLoaded(file:///node_modules/@nativescript/core/ui/frame/frame-common.js:87:0)
System.err:     at (file:///node_modules/@nativescript/core/ui/core/view-base/view-base.js:312:75)
System.err:     at push.../node_modules/@nativescript/core/ui/core/view-base/view-base.js.ViewBase.callFunctionWithSuper(file:///node_modules/@nativescript/core/ui/core/view-base/view-base.js:305:0)
System.err:     at push.../node_modules/@nativescript/core/ui/core/view-base/view-base.js.ViewBase.callLoaded(file:///node_modules/@nativescript/core/ui/core/view-base/view-base.js:312:0)
System.err:     at push.../node_modules/@nativescript/core/ui/frame/frame.js.ActivityCallbacksImplementation.onStart(file:///node_modules/@nativescript/core/ui/frame/frame.js:864:0)
System.err:     at push.../node_modules/@nativescript/core/ui/frame/activity.js.NativeScriptActivity.onStart(file:///node_modules/@nativescript/core/ui/frame/activity.js:29:0)
System.err:     at com.tns.Runtime.callJSMethodNative(Native Method)
System.err:     at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1286)
System.err:     at com.tns.Runtime.callJSMethodImpl(Runtime.java:1173)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:1160)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:1138)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:1134)
System.err:     at com.tns.NativeScriptActivity.onStart(NativeScriptActivity.java:29)
System.err:     at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1514)
System.err:     at android.app.Activity.performStart(Activity.java:7838)
System.err:     at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3398)
System.err:     at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
System.err:     at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
System.err:     at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
System.err:     at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2109)
System.err:     at android.os.Handler.dispatchMessage(Handler.java:107)
System.err:     at android.os.Looper.loop(Looper.java:214)
System.err:     at android.app.ActivityThread.main(ActivityThread.java:7682)
System.err:     at java.lang.reflect.Method.invoke(Native Method)
System.err:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
System.err: Caused by: java.lang.IllegalArgumentException: No view found for id 0x4 (unknown) for fragment FragmentBase_vendor_97639_32_TabFragmentImplementation{a875961 #3 id=0x4 android:bottomnavigation:4:1}
System.err:     at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManager.java:1454)
System.err:     at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1784)
System.err:     at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManager.java:1852)
System.err:     at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:802)
System.err:     at androidx.fragment.app.FragmentManagerImpl.executeOps(FragmentManager.java:2625)
System.err:     at androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2411)
System.err:     at androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2366)
System.err:     at androidx.fragment.app.FragmentManagerImpl.execSingleAction(FragmentManager.java:2243)
System.err:     at androidx.fragment.app.BackStackRecord.commitNowAllowingStateLoss(BackStackRecord.java:654)

**Comment by NickIliev** [comment]
Related to https://github.com/NativeScript/NativeScript/issues/8126

**Comment by a92c** [comment]
is there any news for this bug? Why is it still not solved?
